name = "spinmama-bonus-co-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinmama-bonus.co.cz"
HMAC_KEY = "32f1c770cf05bae821fda1bbd372e11106cd83a53119b3b8925dea0f16e9159f"
COOKIE_NAME = "a01"
PLAY_PATH = "start-now"
BUTTON_ID = "p2f959c29d895d02c7d8f84e38fa77414"
GATE_SALT = "7dec202b1235a353"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "ax2o"
CTA_SELECTOR = ".play-button"
